### ISSUE TITLE
Web client hangs on Congratulation screen after reaching level 2

### ISSUE THREAD

**Issue by jmozgawa** [lgandecki/TheBrain2.0#121]
Clicking on 'Continue Learning' button does nothing.
Page refresh does not help.

![screen shot 2018-01-15 at 01 08 37](https://user-images.githubusercontent.com/6624416/34922474-a5381daa-f990-11e7-95a0-4a99ab4ffb34.png)

**Comment by lgandecki** [comment]
errors in console of either web client or server?

**Comment by jmozgawa** [comment]
It looks like fix is already merged in develop. 
Commit with fix: https://github.com/TheBrainFamily/TheBrain2.0/pull/97/commits/d5155af416ba6b25be5c7bc551f3a73db2b5eeea
