### ISSUE TITLE
Fix unreliable tests

### ISSUE THREAD

**Issue by jmozgawa** [lgandecki/TheBrain2.0#122]
query.Reviews › returns list of reviews grouped by day timestamp
Looks like aforementioned is failing sometimes, probably it is time related issue.

https://circleci.com/gh/TheBrainFamily/TheBrain2.0/1027
https://circleci.com/gh/TheBrainFamily/TheBrain2.0/1029
and
https://circleci.com/gh/TheBrainFamily/TheBrain2.0/1026
https://circleci.com/gh/TheBrainFamily/TheBrain2.0/1028

**Comment by lgandecki** [comment]
I haven't seen this happen since then, closing it for now - when we see other randoms please open up an issue
